services:
  db:
    image: postgres:16
    container_name: art_store_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: art_store

    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    image: art-shop-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  seller-frontend:
    image: art-store-seller-ui
    ports:
      - "3000:80"
    depends_on:
      - backend
  buyer-frontend:
    image: art-store-user-ui
    ports:
      - "3001:80"
    depends_on:
      - backend




volumes:
  postgres_data: