version: "3.9"

services:
  db:
    image: postgres:16
    container_name: art_store_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: art_store

    ports:
      - "543:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: